# Generated by Django 3.2.4 on 2021-08-27 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_styletransfermodel_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='styletransfermodel',
            name='title',
        ),
    ]
