# Generated by Django 3.2.4 on 2021-08-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_styletransfermodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styletransfermodel',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='styletransfermodel',
            name='style',
            field=models.ImageField(upload_to=''),
        ),
    ]
